# Generated by Django 4.1.13 on 2025-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigoshoot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooter',
            name='lname',
            field=models.CharField(default='lastname_needed', max_length=255),
        ),
    ]
