# Generated by Django 4.1.6 on 2023-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigoshoot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='host_round',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
