# Generated by Django 4.1.6 on 2023-02-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigoshoot', '0002_team_host_round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='host_round',
            new_name='host_day',
        ),
    ]
