# Generated by Django 4.1.6 on 2023-02-27 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigoshoot', '0004_remove_score_day1_points_remove_score_day2_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='shooter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='indigoshoot.shooter'),
        ),
    ]
